[package]
name = "elliptical_server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-files = "0.6"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
kdri = { git = "https://github.com/kaegi/kdri" }
anyhow = "1"
